### ISSUE TITLE
Use JSON data for response

### ISSUE THREAD

**Issue by vohmar** [internetee/whois#25]
Drop text source of Unix whois reqests and use JSON instead.

There are two version of whois data for every active domain registration in whois db - in json and in text form. Latter is used by unix whois for very quick responses. But the maintenance overhead to keep this going does not seem to justify the effort.. For this reason we would like to drop the text verision of whois response snapshots and proceed with only json version of whois data.

**Comment by artur-beljajev** [comment]
#375

**Comment by maciej-szlosarczyk** [comment]
This has slightly wider implications, as plain unix body is used also by rest-whois. Instead of generating a template, we traverse each line of whois_record's body and base the response on that. This also needs to be revamped.

https://github.com/internetee/rest-whois/blob/master/app/models/whois_record.rb#L12-L23
